### ISSUE TITLE
rails new

### ISSUE THREAD

**Issue by yuyat137** [TakamotoYurie/be-happy#1]
rails newをしてください！

これとか参考にすると良いかもです
https://blog.toshimaru.net/rails-new-options/

不要なファイルは作られないようにするのと、テストはspecにして欲しいです！
その他にも便利なのがあれば設定してほしいですが、コミットは分けてもらえると！

**Comment by TakamotoYurie** [comment]
RubyとRailsのバージョンどうしますか！

**Comment by yuyat137** [comment]
rails7のviewよくわかんないけど、やってみます？

**Comment by TakamotoYurie** [comment]
不要なファイルは作られないようにするって、
assetsとかhelperですかね（´・ω・｀）

**Comment by yuyat137** [comment]
そうです！

**Comment by TakamotoYurie** [comment]
Ruby 3.1.1
Rails 7でnewします！

**Comment by TakamotoYurie** [comment]
すみません。今更なんですけど、「テストはspec」っていうのは、
RSpecのgemを追加することを指してますか〜？)^o^(

**Comment by yuyat137** [comment]
Rspecは別PRのほうが良いか
このIssueでは、testディレクトリ(Minitest)作らなければOKです！
